on: push
name: Deploy website
jobs:
  upload:
    name: Upload website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: SFTP upload anonpress.org
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: sftp://ftp.anonpress.org/home/anonpress/anonpress.org/
          ftp-username: anonpress
          ftp-password: ${{ secrets.WEB_SFTP_PASSWORD }}
          local-dir: anonpress.org/
          git-ftp-args: --insecure